spring:
  datasource:
    username: root
    password: abc123
    url: jdbc:mysql://39.98.54.68:3306/spring_datasource?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver